### ISSUE TITLE
nomnom dependency is deprecated

### ISSUE THREAD

**Issue by Golmote** [DmitrySoshnikov/regexp-tree#111]
The [nomnom](https://github.com/harthur/nomnom) dependency is deprecated. You should consider switching to [commander](https://github.com/tj/commander.js) or something equivalent.

**Comment by DmitrySoshnikov** [comment]
Cool, thanks for the heads up. Yeah, I think going with `commander` is the right approach. (note to myself: I'll have to replace `nomnom` in all other my projects).

**Comment by Golmote** [comment]
Fixed when #120 was merged.
