### ISSUE TITLE
Optimizer: Must it keep loc values?

### ISSUE THREAD

**Issue by Golmote** [DmitrySoshnikov/regexp-tree#140]
I just found out that `regexp-tree -e "/[0123456789]/" -o` throws an error, because [the `char-class-to-meta` transform tries to rewrite the `loc` values](https://github.com/DmitrySoshnikov/regexp-tree/blob/master/src/optimizer/transforms/char-class-to-meta-transform.js#L44) while the other transforms (specifically the `char-class-classranges-merge` transform in this case) do not set them.

Are the `loc` values something we want to keep accurate during the transformations?
Even in the `char-class-to-meta` transform, where it's handled, shouldn't it need to rewrite the `loc` values of all nodes following the one that's been replaced?

**Comment by DmitrySoshnikov** [comment]
Hm.. interesting. Yeah, I added it initially trying to preserve a "parsed state", but I think we actually don't need one in this case, and it safely can be removed. Trying to keep the locations adjusted will just make transforms harder to follow with no good reason.
