### ISSUE TITLE
Parser: Capturing groups: throw on Unicode escape name if no `u` flag

### ISSUE THREAD

**Issue by DmitrySoshnikov** [DmitrySoshnikov/regexp-tree#143]
See: https://tc39.github.io/proposal-regexp-named-groups/#sec-patterns-static-semantics-early-errors

This seems should throw:

```
/(?<\u{41}>)\k<\u{41}>/
```

But this should work:

```
/(?<\u{41}>)\k<\u{41}>/u
```

**Comment by DmitrySoshnikov** [comment]
@mathiasbynens, can you confirm please?

CC @Golmote, @nicolo-ribaudo

**Comment by mathiasbynens** [comment]
Confirmed. Note that `/\u{41}/` by itself [does not throw](https://mathiasbynens.be/notes/es6-unicode-regex#impact-syntax), though — please take care not to change that behavior.

cc @littledan

**Comment by DmitrySoshnikov** [comment]
@mathiasbynens, thanks; yeah, `/\u{41}/` by itself doesn't throw, and it's correctly handled already.

**Comment by DmitrySoshnikov** [comment]
Fixed in https://github.com/DmitrySoshnikov/regexp-tree/commit/1badfb5e3da94b2342c701b9ef92fbfa3e5f3ca5.
