### ISSUE TITLE
Interested in more examples?

### ISSUE THREAD

**Issue by davisjam** [DmitrySoshnikov/regexp-tree#154]
This is just a question.

I've written two small scripts based on the traversal API.

1. Script 1 implements substack's [safe-regex](https://github.com/substack/safe-regex) project, but it fixes the known bugs in that program.
2. Script 2 checks for the presence of certain assertion types in a regex.

Both use pre-processing that converts (some) Python syntax into regexp-tree syntax.

@DmitrySoshnikov Would you like these scripts in `examples/`?

**Comment by DmitrySoshnikov** [comment]
@davisjam, yep, good idea, the more good practical examples, the better!

Re: `safe-regex`, I see it uses `ret` package as a dependency, which is a "regexp tokenizer", and can be limited by not having full AST. If you fix some issues in that program, this is awesome!

**Comment by davisjam** [comment]
I have submitted PRs to `safe-regex`. The author appears to have abandoned it.

`safe-regex` is actually how I found `regexp-tree` -- dissatisfaction with `ret` led me here.

**Comment by davisjam** [comment]
> Yep, good idea, the more good practical examples, the better!

OK. I'll open a PR in a few days.

**Comment by davisjam** [comment]
@DmitrySoshnikov FYI I now have publish rights to `safe-regex` and am working on a new version that uses `regexp-tree` and embeds the examples we talked about in #159.

**Comment by DmitrySoshnikov** [comment]
@davisjam, this sounds great! Let me know in case you'll need any support or help.
