### ISSUE TITLE
Wrong sorting/optimization

### ISSUE THREAD

**Issue by denisx** [DmitrySoshnikov/regexp-tree#163]
Using BrainMaestro/eslint-plugin-optimize-regex (which use your library)

catch a bug:
[^a-zа-яё -]+/gi
wants to be
[^ -a-zа-яё]+/gi
then wants to be
/[^ -azа-яё]+/gi

**Comment by DmitrySoshnikov** [comment]
@denisx, thanks, I'll try to take later on into this. At will of course appreciate a PR in case you'll reach it earlier.

**Comment by PopGoesTheWza** [comment]
Another erroneous sort/optimization:

```shell
npx regexp-tree-cli -e '/[0-9\-a-z]/' -o

 Optimized: /[\d-a-z]/
```

Here the unescaped `-` should be first within the class. The actual result no longer match `b` or `y` (among others).

**Comment by DmitrySoshnikov** [comment]
Thanks, I'll take a look at this today.

**Comment by DmitrySoshnikov** [comment]
This should be fixed in https://github.com/DmitrySoshnikov/regexp-tree/commit/db6865241e8ff044804e62869e9d091ce2e5b80d and published in `v0.1.18`. Please let me know if you find any issue there.

**Comment by JounQin** [comment]
@DmitrySoshnikov Would you like to take a look for https://github.com/sindresorhus/eslint-plugin-unicorn/issues/499?

`/[\d-a-z]/` and `/[-\da-z]/` are different in damn JavaScript.

**Comment by PopGoesTheWza** [comment]
Given `/[0-9\-a-z]/` as input, valid JavaScript compatible optimization would be `/[\d\-a-z]/`, `/[-\da-z]/` or `/[\da-z-]/`

Moving the unescaped dash to first or last position would be nice but is likely to require extra checks (i.e. negate range starting with a caret)

**Comment by DmitrySoshnikov** [comment]
Thanks, I'll take a look.

**Comment by DmitrySoshnikov** [comment]
OK, should be fixed in https://github.com/DmitrySoshnikov/regexp-tree/commit/8826c9e94323a918a4da01a1f2a83ab2d46e59c1, and in `v0.1.19`.

**Comment by JounQin** [comment]
@DmitrySoshnikov Does it cover `[-\da-z]`?

![image](https://user-images.githubusercontent.com/8336744/74396240-59d78900-4e4c-11ea-9b8f-1f67688b7200.png)

**Comment by DmitrySoshnikov** [comment]
ah, that's another one, OK, I'll take a look at `[-\da-z]`

**Comment by JounQin** [comment]
@denisx And https://github.com/sindresorhus/eslint-plugin-unicorn/issues/477 🤣

**Comment by DmitrySoshnikov** [comment]
@JounQin, OK, should be fixed in https://github.com/DmitrySoshnikov/regexp-tree/commit/091d4e9083abbc9f9573053d220c8a3db1fb3308 and in `v0.1.20`. Can you double-check please? I'll close the issue after it.
