### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by Fazerty** [DmitrySoshnikov/regexp-tree#166]
Hello,

I'm creating in typescript a library ([phrasalExpressions](https://github.com/Fazerty/phrasalExpressions)) similar to JSVerbalExpressions using regexp-tree.

Is it possible to export interfaces (so I hadn't to do it in [interfaces.ts)](https://github.com/Fazerty/phrasalExpressions/blob/master/src/ast/interfaces.ts) ?

Is it possible to rename Regexp interface to AstRegexp for example to avoid confusion?

Is possible to export other functions ? (see in [phrasalexpresssions.ts](https://github.com/Fazerty/phrasalExpressions/blob/master/src/phrasalexpressions.ts) from line 56).
I need at least these two to be added:
`  export function generate(ast: AstRegExp): string;`
`  export function toRegExp(regexp: string): RegExp;`

For the SimpleQuantifier interface is it possible to add the '?' kind?

In the RangeQuantifier  is it possible to make the 'to' parameter optional?

Thanks
Best Regards.

**Comment by DmitrySoshnikov** [comment]
Hi, @Fazerty 

> I'm creating in typescript a library (phrasalExpressions) similar to JSVerbalExpressions using regexp-tree.

Looks like a great module, congrats!

> Is it possible to export interfaces (so I hadn't to do it in interfaces.ts) ?

@RReverser at some point added TypeScript's annotations, [here](https://github.com/DmitrySoshnikov/regexp-tree/blob/master/index.d.ts). We should probably revisit it, and adjust with your [interfaces.ts](https://github.com/Fazerty/phrasalExpressions/blob/master/src/ast/interfaces.ts) if it makes more sense. I'll appreciate a PR for this.

> Is possible to export other functions ?

Both `generate`, and `toRegExp` should be [exposed](https://github.com/DmitrySoshnikov/regexp-tree/blob/master/src/regexp-tree.js#L104-L116) in the main module. Let me know if this doesn't work.

> For the SimpleQuantifier interface is it possible to add the '?' kind?

Currently the following:

```
regexp-tree -e '/a?/'
```

Parses it to the:

```json
{
  "type": "RegExp",
  "body": {
    "type": "Repetition",
    "expression": {
      "type": "Char",
      "value": "a",
      "kind": "simple"
    },
    "quantifier": {
      "type": "Quantifier",
      "kind": "?",
      "greedy": true
    }
  },
  "flags": ""
}
```

which seems is already of `?` for the `kind`. Let me know if anything is missing.

> In the RangeQuantifier is it possible to make the 'to' parameter optional?

The following:

```
regexp-tree -e '/a{1,}/'
```

is parsed into:

```json
{
  "type": "RegExp",
  "body": {
    "type": "Repetition",
    "expression": {
      "type": "Char",
      "value": "a",
      "kind": "simple"
    },
    "quantifier": {
      "type": "Quantifier",
      "kind": "Range",
      "from": 1,
      "greedy": true
    }
  },
  "flags": ""
}
```

which already has `to` optional. So if you could more clarify, would be great.

**Comment by Fazerty** [comment]
All the comments I did were for the typescript definition file.
generate, and toRegExp are exposed in the main module but not exported in the index.d.ts.
 ? for the kind  of SimpleQuantifier is missing in the index.d.ts.
In the RangeQuantifier interface in the index.d.ts the 'to' parameter is not optional

So I changed the index.d.ts and I did a pull request.
