### ISSUE TITLE
Open to splitting the CLI into its own repository?

### ISSUE THREAD

**Issue by realityking** [DmitrySoshnikov/regexp-tree#170]
`regexp-tree` recently became a dependency of `@babel/preset-env`. Currently the module combines the CLI and the library, which brings in dependencies that are only required. Would you be open to splitting it into separate repositories or two npm packages in a monorepo?

I'm happy to do the leg work for this but it's a bit too much work to just make a proposal without asking first. 🙂

**Comment by DmitrySoshnikov** [comment]
@realityking, yes, I was actually thinking about this already. Splitting the CLI (into its own `regexp-tree-cli`) definitely makes sense. In addition moving forward, I think we can also separate interpreter module, etc into own sub-packages.

And yes, I'll appreciate a PR of course for this -- we can start from separating the CLI. Two separate packages with the monorepo sounds good.

**Comment by DmitrySoshnikov** [comment]
The CLI is moved to the https://github.com/DmitrySoshnikov/regexp-tree-cli. I'll publish it soon, and will remove CLI-related dependencies from the original `regexp-tree` package.

**Comment by DmitrySoshnikov** [comment]
Fixed in https://github.com/DmitrySoshnikov/regexp-tree/commit/367668980d74bf2483d5fbc15d517ea0e9b6d3c3, published in `v.1.1.3`.

**Comment by realityking** [comment]
Thank you! And sorry I wasn't able to help, life got in the way the last few weeks.

**Comment by DmitrySoshnikov** [comment]
@realityking, no problem, and thanks for the report and suggestion!
