### ISSUE TITLE
Error: Cannot find module 'cli-table3'

### ISSUE THREAD

**Issue by panhezeng** [DmitrySoshnikov/regexp-tree#172]
@babel/plugin-transform-named-capturing-groups-regex
dependencies
regexp-tree

regexp-tree TablePrinter
dependencies
cli-table3

but package.json peerDependencies or dependencies no cli-table3

require.context("@/config/vuex/types/", false, /(?<!index)\.js$/)

npm run dev

Error: Cannot find module 'cli-table3'

**Comment by DmitrySoshnikov** [comment]
Fixed in https://github.com/DmitrySoshnikov/regexp-tree/commit/f1fca64fc32436c047d55816ea6121487812a425, and in `v1.1.5`.
