### ISSUE TITLE
Cannot parse unicode property escapes

### ISSUE THREAD

**Issue by ajafff** [DmitrySoshnikov/regexp-tree#176]
The following regular expressions cannot be parsed:
```js
/\p{Lu}/u
/\p{Script=Greek}/u
```
https://astexplorer.net/#/gist/68b236a1dd356b9194a456de5ce9e7ed/e0ef2417e9a21e948ecd102744ef3b3f3b77274b

As of ES2018 this is valid sytax: https://github.com/tc39/proposal-regexp-unicode-property-escapes

**Comment by DmitrySoshnikov** [comment]
@ajafff, thanks for the report, I'll take a look (and will appreciate a PR in case you reach it earlier than me).

**Comment by DmitrySoshnikov** [comment]
Working on it..
