### ISSUE TITLE
Invalid optimizations involving backreferences

### ISSUE THREAD

**Issue by ajafff** [DmitrySoshnikov/regexp-tree#180]
```
▶ regexp-tree-cli -e '/(.)\1(?:0)/' -o

 Optimized: /(.)\10/ 

▶ regexp-tree-cli -e '/(.)\1[0]/' -o

 Optimized: /(.)\10/ 
```

This changes the backreference followed by a `0` to an octal escape `10`. With the `u` flag this would actually be a syntax error.

**Comment by DmitrySoshnikov** [comment]
Thanks, yes, clearly a bug. Will try to take a look, and will appreciate a PR in case.

The transforms causing issues:

- [char-class-to-single-char-transform](https://github.com/DmitrySoshnikov/regexp-tree/blob/master/src/optimizer/transforms/char-class-to-single-char-transform.js)
- [ungroup-transform](https://github.com/DmitrySoshnikov/regexp-tree/blob/master/src/optimizer/transforms/ungroup-transform.js)

**Comment by DmitrySoshnikov** [comment]
Fixed in https://github.com/DmitrySoshnikov/regexp-tree/commit/9b75a48b819e958e4a6b40f9784577b704939c08 and in `v0.1.16`.
