### ISSUE TITLE
BUG: Large RegExp errors

### ISSUE THREAD

**Issue by nebrelbug** [DmitrySoshnikov/regexp-tree#188]
I have a large Regular Expression (generated by precompiling a Moo lexer) that doesn't minify as expected. See https://runkit.com/nebrelbug/regexp-tree-bug

**Comment by DmitrySoshnikov** [comment]
Thanks for the report. Fixed in https://github.com/DmitrySoshnikov/regexp-tree/commit/1cc59724c38d8d059cf89a26c293365419dc8d60 and `v0.1.14`.

**Comment by nebrelbug** [comment]
@DmitrySoshnikov thanks! It's working great :smile:

Thanks for the amazing tool!
