### ISSUE TITLE
Bad replacement: `/(_|[^\s\w])/g` => `/([\s\w])/g`

### ISSUE THREAD

**Issue by mikestopcontinues** [DmitrySoshnikov/regexp-tree#198]
Hey, neither one of the changes suggested preserve the functionality of the pattern. I expect it to match everything except whitespace, letters, and numbers. The change almost completely inverts that.

`/(_|[^\s\w])/g` => `/([\s\w])/g`

I solved the problem with `/[^\d\sA-Za-z]/g`, which is ultimately easier to read. I would argue this might serve as the expected result in a test.

Running v0.1.11 via https://github.com/BrainMaestro/eslint-plugin-optimize-regex

Thanks!

**Comment by DmitrySoshnikov** [comment]
Thanks for the report. Fixed in https://github.com/DmitrySoshnikov/regexp-tree/commit/0fd2c68f880bd0f40f2beec9b64ef81ab4fffb80 and published in `v0.1.15`.

**Comment by mikestopcontinues** [comment]
Apologies! Thanks!
