### ISSUE TITLE
Version incompatibility between npm and Git

### ISSUE THREAD

**Issue by brettz9** [DmitrySoshnikov/regexp-tree#203]
On Git, the `package.json` in `master` shows 0.1.19 (though there is a 0.1.20 tag) and npm has 0.1.20. Can I ask why this is the case?

Thanks!

**Comment by DmitrySoshnikov** [comment]
Hm.. Thanks, yeah, seems a bad rebase/commit issue. The correct version should be 0.1.20. Can you send a PR please with updating to 0.1.20? Otherwise, I'll do this later once at laptop.

**Comment by brettz9** [comment]
Do you want me to rebase master onto the 0.1.20 tag?

**Comment by DmitrySoshnikov** [comment]
Ah, I've pushed https://github.com/DmitrySoshnikov/regexp-tree/commit/a82ff3d039bc51e044e492b29ac8248bcd1ee61f which fixes it. Can you rebase please?
