### ISSUE TITLE
Broken optimize with multiple optional whitespace `\s`

### ISSUE THREAD

**Issue by Cherry** [DmitrySoshnikov/regexp-tree#216]
This was first noticed in https://github.com/sindresorhus/eslint-plugin-unicorn/issues/994

Optimising `/\s?\s?/` results in an invalid regexp:

```js
const {optimize} = require('regexp-tree');
const result = optimize(/\s?\s?/);
/*
_ast: {
    type: 'RegExp',
    body: { type: 'Alternative', expressions: [Array] },
    flags: ''
  },
  _source: null,
  _string: '/\\s?{2}/',
  _regexp: null,
  _extra: null
*/
```

The optimized result is `/\s?{2}/`, which isn't valid and throws a `Invalid regular expression: /\s?{2}/: Nothing to repeat` error. I believe `\s{0,2}` would be the correct optimization here.

**Comment by Cherry** [comment]
On further investigation, this appears to impact a lot of character classes:

`/\w?\w?/` for example, as well as `\r`, `\n`, `\v`, etc.

**Comment by DmitrySoshnikov** [comment]
Thanks for the report, I'll try to take a look sooner in this issue, and would appreciate a PR in case 😄

**Comment by DmitrySoshnikov** [comment]
In fact, to avoid syntax error that should be wrapped into non-capturing group -- `/(?:\s?){2}/`, at which point I'm not sure if it's a good optimization. The easiest way is just to skip these classes from optimization, or (more complicated) -- to wrap them into the non-capturing group as long as they are repeated more than two times.

**Comment by DmitrySoshnikov** [comment]
Fixed in https://github.com/DmitrySoshnikov/regexp-tree/commit/0421d57324defe30ff15a5dbb5af5c08f751a795 and `v0.1.22`.
