### ISSUE TITLE
optimizer incorrectly proposes rewrite .|[\r] as [.\r]

### ISSUE THREAD

**Issue by urchick** [DmitrySoshnikov/regexp-tree#227]
optimizer proposes replacing `.|[\r]` with `[.\r]` which is obviously incorrect as `.` plays different roles in these contexts

**Comment by DmitrySoshnikov** [comment]
@urchick thanks for the report, seems disjunction merger should escape the `\.`. I'll take a look, and will appreciate a PR for this in case.

**Comment by Maxim-Mazurok** [comment]
Running into the same issue, suggests to replaces `(.|\s)` with `[.\s]` which doesn't work

**Comment by DmitrySoshnikov** [comment]
@Maxim-Mazurok thanks - feel free to send a PR for this.

**Comment by Maxim-Mazurok** [comment]
> optimizer proposes replacing `.|[\r]` with `[.\r]` which is obviously incorrect as `.` plays different roles in these contexts

I'm unable to reproduce this. For `/.|[\r]/` I'm getting `/.|\r/` which seems to be correct.

Mine also doesn't reproduce actually.

Only this one does: `/(?:.|\s)/` => `/[.\s]/`
