### ISSUE TITLE
Parser: support "dotAll" \s flag

### ISSUE THREAD

**Issue by DmitrySoshnikov** [DmitrySoshnikov/regexp-tree#26]
The new "dotAll" `\s` flag matches all symbols, including line terminators (https://github.com/mathiasbynens/es-regexp-dotall-flag). This proposal is at stage 3, so it's safe to add it. NOTE: `toRegExp` won't work with it, but having it in parser is fine.

**Comment by shvaikalesh** [comment]
With current API we can transpile `/s` like this:

```js
let ast = RegExpTree.parse("/.[.]/is")
let dotAll = ast.flags.includes("s")

ast.flags =
ast.flags.replace("s", "")

let isMetaDot = node =>
  node.type == "Char" &&
  node.kind == "meta" &&
  node.value == "."

RegExpTree.traverse(ast, {
  onChar(node) {
    if (dotAll && isMetaDot(node)) {
      node.type = "CharacterClass"
      node.negative = true
    }
  },
})

RegExpTree.generate(ast) // => /[^][.]/i
```

We have to remove `/s` flag, thus we can't use planned `transform` API (or plugins).
Something like `onFlag` would come handy:

```js
let dotAll = false
let isMetaDot = // same

RegExpTree.transform("/.[.]/is", {
  onFlag(node) {
    if (node.type == "dotAll") {
      node.remove()
      dotAll = true
    }
  },
  onChar(node) {
    // same
  },
}) // => /[^][.]/i
```

A lot of new RegExp proposals work only if `/u` is present, so they would need access to flags too.

**Comment by DmitrySoshnikov** [comment]
Yeah, perhaps we can expose `onFlag` hook, although each flag is not a real node. Probably a flag node will be just a flag value:

```js
if (node === 's') {
  this.remove(node);
}
```

One issue with the approach above, is the `dotAll` flag might be set not at needed time: if flags are handled last, then the `onChar` will be executed when `dotAll` is not yet set. From this perspective, either flags should always be handled first (prior any other node), or just expose several methods to manipulate them. An actual `ast` can also be exposed, so the handlers can just access `ast.flags`, and manipulate/rewrite them.

Alternatively, a plugin/handler should not be even executed if some condition is not met (e.g. if some flag is not present). So probably `shouldRun` generic hook can be exposed too:

```js
RegExpTree.transform("/.[.]/is", {
  /**
   * Whether this handler should be executed.
   */
  shouldRun(ast) {
    return ast.flags.includes('s');
  },
  
  /**
   * Generic init hook ran prior any other nodes.
   */
  init(ast) {
    ast.flags = ast.flags.replace('s', '');
    // Or expose some API methods:
    // this.removeFlag('s');
  },

  onChar(node) {
    if (...) {
      // `remove`, `replaceWith`, etc. methods can either be
      // attached on a node itself, or on `this` value (which is the handler object). 
      this.replaceWith({
        type: 'CharacterClass',
        negative: true,
      })
    }
   }
});
```

**Comment by DmitrySoshnikov** [comment]
Actually, I just though, the `RegExp` node itself can play role of the `init` hook, since it's the first node which is handled, and flags can be handled there as well.

```js
onRegExp(node) {
  ast.flags = ast.flags.replace('s', '');
  // Or expose some API methods:
  // this.removeFlag('s');
}
```

**Comment by shvaikalesh** [comment]
Right, `onFlag` is suboptimal. Pseudo-nodes and reversed (to source code) callback ordering is not cool.

> `RegExp` node itself can play role of the `init` hook

This is 🔥  awesome, totally solves mentioned cases.
