### ISSUE TITLE
NodePath.getNextSiblingNode() returns a Node but a NodePath would be more useful

### ISSUE THREAD

**Issue by hg42** [DmitrySoshnikov/regexp-tree#38]
if you want to go through siblings you need a NodePath to invoke getNextSiblingNode() again.

So, I would suggest getNextSibling() returning a NodePath.

**Comment by DmitrySoshnikov** [comment]
Yeah, I was thinking about it, however, it's not clear yet how to access exactly a "next" sibling if hasn't been handled yet. Nodes run in order (including in a collection), and a `NodePath` is [created](https://github.com/DmitrySoshnikov/regexp-tree/blob/master/src/traverse/index.js#L84) prior passing to a handler. If we have a collection of `[a, b, c]`, and being on `b` node, we haven't yet started handling the `c` node, so its `NodePath` doesn't exist yet.

I definitely agree having a sibling as a `NodePath` would be much more convenient, however, need to solve this issue first. It could be should be 2-pass traversal, which is bad; perhaps we also need more specific traversal logic, and don't depend on `ast-traverse` module.

**Comment by DmitrySoshnikov** [comment]
Actually... we can probably create an actual `NodePath` if it doesn't exist in the [registry](https://github.com/DmitrySoshnikov/regexp-tree/blob/master/src/traverse/index.js#L13) on `getNextSibling`. For this the registry should not be private for traverse, but probably live in the `NodePath` itself. Then when node `c` will be handling, it already will get an existing `NodePath` from the registry. It might be deleted though already, so we'll also need to check if a node/path was deleted in some handler.

**Comment by hg42** [comment]
I had similar ideas...

however, my need for that has gone away now.

I wanted to implement the extended regexps (x-flag) with whitespace and comments.
Whitespace is the problem with deleting itself.

Comments would be a sequence of characters starting with # and stopping with \n, for which I would have to go to the following siblings.

But comments can also contain illegal constructs which stop parsing. So I have to do this on the regexp string first, which already works well (enough).

Ideally, this would be handled in the parser.
But this would make the syntax definition dependend on a flag.

**Comment by DmitrySoshnikov** [comment]
The multiline regexes with comments is something I was thinking as well, although it's not yet supported by ECMAScript/JavaScript (`regexp-tree` is based on its grammar yet, though probably not limited to it, and non-standard features like `x` flag, etc. can be added).

As for comments, Syntax supports _states_ in tokenizer. This means a tokenizer can enter the "comment" state ([example](https://github.com/DmitrySoshnikov/syntax/blob/master/examples/lexer-start-conditions.g.js#L82)), and all symbols inside a comment can be treated differently. Or comments can be just skipped at all ([example](https://github.com/DmitrySoshnikov/mips-parser/blob/master/mips.g#L22)). So it will be possible to handle in the parser.

**Comment by DmitrySoshnikov** [comment]
OK, it should be fixed in https://github.com/DmitrySoshnikov/regexp-tree/commit/9859d991bd20f98f863ca6559dbd932a152a1d69 (and in `0.0.28`). Please let me know if you see any issues.
