### ISSUE TITLE
Implement interpreter module

### ISSUE THREAD

**Issue by DmitrySoshnikov** [DmitrySoshnikov/regexp-tree#42]
This is a large size issue, but eventually we'll need to have an _interpreter_ in order to test new features (like lookbehind assertions, named groups, etc) which are not yet implemented in JS engines. 

The spec is [here](http://www.ecma-international.org/ecma-262/7.0/#sec-pattern-semantics). We can follow the ECMAScript spec, though can also simplify the handling, as long as the semantic is preserved.

```js
const regexpTree = require('regexp-tree');

// Lookbehind.
regexpTree.test('/(?<=a)b/', 'ab'); // true

// Named groups.
const match = regexpTree.exec('/(?<data>x)/', 'x'); // MatchResult

console.log(match[0]); // x
console.log(match.groups.data); // x
```

A separate engine (using NFA/DFA) can be implemented in another module.

**Comment by hg42** [comment]
very ambitious :-)

I think I am kind of alienating it from its original purpose.
I wonder, what you originally intended, when you  created regexp-tree.
Is it a project you need for ast-explorer?

The syntax is bound to a single syntax definition, right?
At some point I thought it would be nice, if we could switch the syntax.
And the user could need to extend the definition in some way, e.g. to play with new features.

**Comment by DmitrySoshnikov** [comment]
> I wonder, what you originally intended, when you created regexp-tree.

Initially was needed just a parser, but still wanted to build a simple NFA/DFA for educational purposes (with potentially teaching the topic in a class). There is a [small intro article](https://medium.com/@DmitrySoshnikov/regexp-tree-a-regular-expressions-parser-with-a-simple-ast-format-bcd4d5580df6) on it as well.

> Is it a project you need for ast-explorer?

Not really; for AST Explorer we need just the parser, and transform API (for quick transform examples -- AST Explorer is very useful for it, and support multiple ASTs from different languages).

> The syntax is bound to a single syntax definition, right?
At some point I thought it would be nice, if we could switch the syntax.
And the user could need to extend the definition in some way, e.g. to play with new features.

Currently it aims ECMAScript (JavaScript) regexes, since I took [its grammar](http://www.ecma-international.org/ecma-262/7.0/#sec-patterns) initially to build the parser. However, it's possible we'll be able to deviate to a more powerful regular expressions, supporting multiline, comments, etc.

This can be done by having different modes (PCRE, JavaScript, etc).

> very ambitious :-)
I think I am kind of alienating it from its original purpose.

Yeah, that's said, it's kind of a big issue :) But it's still will be nice to have to test new features, which aren't supported yet (i.e. which still are in proposal stage for standardization).

**Comment by hg42** [comment]
> This can be done by having different modes (PCRE, JavaScript, etc)

but it's not possible currently, right?
or did I miss something (again)?

I see at least two reasons for switching syntax definitions:
* different engines or specs
* different flags (mainly the x-flag)

most flavours have only small changes, like `(?P<name>...)` vs. `(?<name>...)`.
Does the parser generator allow such variations?

**Comment by DmitrySoshnikov** [comment]
> but it's not possible currently, right?

Nope, currently only JavaScript regexes are supported. But I can imaging, the parsing `mode` could be as:

```js
// Parse in PCRE mode.
regexpTree
  .parser
  .setOptions({
    captureLocations: true,
    mode: 'PCRE',
  })
  .parse(regexp);
```

And this will enable PRCE syntax. Thus, we don't need to over-complicate the current grammar for ECMAScript, but instead create an own version, and then based on `mode` just call a needed parser.

With all this, `traverse`, and `transform` modules can be completely generic, and be used with any parser mode. Code generate should be own though.

So the structure likely will be:

```
├── parser
    ├── pcre
    ├── python
    ├── javascript
       ....
```

The same for generator.

With this we can add `x` flag, comments, etc. Moreover, it can be any other custom mode, when we can experiment with other non-standard features.

**Comment by hg42** [comment]
some modes have sub-modes (only `x`-flag for now), so the tree may be more like this:
```
├── parser
    ├── pcre
        ├── x
    ├── python
        ├── x
    ├── javascript
```
or may be:
```
├── parser
    ├── pcre
    ├── pcre-x
    ├── python
    ├── python-x
    ├── javascript
```

or the `x`-flag could be expressed inside the syntax (if possible, that's why I asked about runtime controllable variations in the grammar, I probably didn't ask clear enough).

Most parser generators don't allow such things.

The `x`-flag makes a big difference in parsing, either there is some collected whitespace, newline, a comment, or there is a sequence of characters or even other syntax elements, because comments could contain everything. So it looks like a complete new grammar, but sharing a lot.

I think, usually this particular case would be solved in the tokenizer. E.g. it would collect whitespace or a comment if the `x`-flag is set. Whitespace is tricky because it's different in character classes. The tokenizer would also become dependent on context.

The grammar could profit from a kind of derivation (mixins, includes, modules, classes, ...) to be able to share common parts of grammars. Then it should be simple and effortless to express variations like `x`-flag mode etc based on common grammar parts.

I would prefer having common parts at only one place, so bugs can be fixed for all at once and you can better see and manage the differences between grammars.

**Comment by DmitrySoshnikov** [comment]
> some modes have sub-modes (only x-flag for now)

OK, yeah, then per-language there might be parser options (and `x` can go there).

> or the x-flag could be expressed inside the syntax (if possible, that's why I asked about runtime controllable variations in the grammar, I probably didn't ask clear enough).
Most parser generators don't allow such things.

Yes, it'd be impractical to generate statically a parser per each flag, so this should be runtime-controllable.

Currently _Syntax_ (the parser generator we use) supports only setting "global options" per the whole parser module. I was thinking we probably can pass also options per-each `parse` call.

```js
regexpTree
  .parser
  .setOptions({
    captureLocations: true,
    syntax: 'python',
  })
  .parse(string, {
    'enable-x-flag': true,
  });
```

Or alternatively can go also to the global options if this works (although, global options are preserved between `parse` calls). Then, we have [onParseBegin](https://github.com/DmitrySoshnikov/regexp-tree/blob/master/src/parser/regexp.bnf#L132) hook (which is called each time on `parse` call), where we could analyze the options, and set needed state in tokenizer.

> I think, usually this particular case would be solved in the tokenizer. ... The tokenizer would also become dependent on context.

Yes, _Syntax_ supports [tokenizer states](https://github.com/DmitrySoshnikov/syntax#start-conditions-of-lex-rules-and-tokenizer-states) (i.e. making it kinda "context-sensitive").

We already use e.g. [class](https://github.com/DmitrySoshnikov/regexp-tree/blob/master/src/parser/regexp.bnf#L25-L39) state in the _regexp-tree_, so e.g. `(`, and `)` parens yield different token types whether we're in a character class (where it's a simple char), or in normal pattern (where it's a grouping paren).

So, if we have options, we can enter needed tokenizer state in the `onParseBegin`, e.g.:

```js
yyparse.onParseBegin = (string, tokenizer, options) => {
  if (options['x-flag-enabled']) {
    tokenizer.pushState('x-flag');
  }
};
```

And then in the tokenizer we'll be able to use:

```
\s+                     return 'CHAR'
<x-flag>\s+      /* skip whitespace */
```

Or probably simply:

```
\s+  {
  if (this.getCurrentSate() === 'x-flag') {
    /* skip whitespace if `x` is set */
    return null;
  }

  // Otherwise, it's a simple char.
  return 'CHAR';
}         
```

Similarly, the BNF grammar rules may have some extra handling, and produce different AST node types if we're currently in some state.

> The grammar could profit from a kind of derivation (mixins, includes, modules, classes, ...) to be able to share common parts of grammars. Then it should be simple and effortless to express variations like x-flag mode etc based on common grammar parts.

Mixing/includes, etc is a good idea actually, I'll think about it.

**Comment by hg42** [comment]
I think, the only flag changing the parser is `x`-flag. So different  parsers could be an option.

There is also a feature in perl/PCRE: `(?f)` where f is a flag.
http://pcre.org/current/doc/html/pcre2syntax.html#SEC16
http://pcre.org/current/doc/html/pcre2syntax.html
I am not sure where these can occur, but I think that at least `i` can be used in groups. so `((?i)BLA)` would ignore case and `((?-i)BLA)` wouldn't. Fortunately the parser doesn't know about `i`-flag (I think). But seems like `x`-flag could be used the same, so the sytax would change while parsing. Which makes it necessary, to use runtime mode of tokenizer.

pcre is very powerful. So there might be difficult situations.

**Comment by hg42** [comment]
Please note, most what I am saying here aims at giving you input.
These are not suggestions I would want to see implemented.
So don't feel pushed in such directions in any way.

My own interests seem to be very different from yours.

I want to get the most out of javascript RegExps, because I am used to have better regexp support.

I need named groups.
The x-flag would be nice, I like to write regexps with whitespace and comments.
I am also missing some replace operations.

And I desperately need getting positions for every group result, so I can split a string by the positions where those groups were found. javascript only gives you the position of the whole regexp.

The group positions are not solved by any other regexp extension libraries yet.

The only way I see to implement this with javascript RegExp is by wrapping everything in groups and cummulating lengths of the resulting strings (which is further complicated by nested groups that are returned in sequentially). I also want to combine adjacent wrapped groups to simplify the expression (which is faster than having each character in a group).
Your library is the solution to these operations.

The x-flag would be nice to have in the parser, but it is not really necessary (for me), because it can be implemented by replacing comments in the regexp text and remove whitespace in the tree under certain conditions.

**Comment by DmitrySoshnikov** [comment]
FYI: since https://github.com/DmitrySoshnikov/syntax/commit/1c48d76f0d4a73fbb2fd0aa5e5223134b5f17bf2 (Syntax), and https://github.com/DmitrySoshnikov/regexp-tree/commit/b8db3c4d6326e86040cf1ce528e358aa581c6861 (regexp-tree) options per `parse` call are available.

**Comment by DmitrySoshnikov** [comment]
> Please note, most what I am saying here aims at giving you input.
These are not suggestions I would want to see implemented.
So don't feel pushed in such directions in any way.

My own interests seem to be very different from yours.

No-no, I actually very appreciate your ideas :) and by discussing it, we can route the implementation as needed too (e.g. I didn't have initial plans to build language-agnostic regexp processor, and now I do -- supporting several syntax plugins, and different modes, like `x`, etc).

My goal is to provide a useful regexp processing library, which can be useful for any purposes. The use-case you describe (to have more powerful regexes by transforming to equivalent "desugared" version) is definitely one of them. Also, support in editors for better regexp highlight, for minifiers, etc.

> The x-flag would be nice, I like to write regexps with whitespace and comments.

For sure, in other languages I used `x` flag as well.

> I am also missing some replace operations.

Have an example?

> The group positions are not solved by any other regexp extension libraries yet.

Yeah, JS regexes are pretty limited today. This might be added in the future version of ECMAScript. At the moment, named groups, `s` flag, and lookbehind assertions are being standardized.

> The only way I see to implement this with javascript RegExp is by wrapping everything in groups and cummulating lengths of the resulting strings (which is further complicated by nested groups that are returned in sequentially)

Yeah, this is pretty nasty, but might be a good as a workaround. That's why having the interpreter module implemented will allow also running such regexes. Potentially one would be able to just replace global `RegExp` constructor from _regexp-tree_, and get a working version:

```js
// Replace global RegExp
RegExp = regexpTree.RegExp;

const re = new RegExp('(?<year>\\d{4})-(?<month>\\d{2})-(?<day>\\d{2})');

re.test('20017-04-21'); // true
```

> The x-flag would be nice to have in the parser, but it is not really necessary (for me), because it can be implemented by replacing comments in the regexp text and remove whitespace in the tree under certain conditions.

Definitely a good workaround, though it'd still be nice to support it in the parser for different syntaxes.

**Comment by hg42** [comment]
```js
const re = new RegExp('(?<year>\\d{4})-(?<month>\\d{2})-(?<day>\\d{2})');
re.test('20017-04-21'); // true
```
I hope not "working" like this :-)

Sorry about the replacement operations, I don't remember...

**Comment by DmitrySoshnikov** [comment]
This will be split on NFA/DFA implementation, and ECMAScript recursive implementation. Closing this one, and will be tracking each separately. See #86 for NFA/DFA.
