### ISSUE TITLE
Implement Babel plugin for optimizer

### ISSUE THREAD

**Issue by DmitrySoshnikov** [DmitrySoshnikov/regexp-tree#51]
[Optimizer](https://github.com/DmitrySoshnikov/regexp-tree/tree/master/src/optimizer) module can be used in JS code, e.g. via [Babel](https://babeljs.io/) plugin handling [RegExpLiteral](http://astexplorer.net/#/gist/a90a50a08a99b8d728183e0b6f52a012/17f2b9b22b2acdd9d6d5305c9fc0b181533ffee7) node, and replacing its `pattern` property.

The plugin is a separate package and is in [src/optimizer/babel](https://github.com/DmitrySoshnikov/regexp-tree/tree/master/src/optimizer/babel).

**Comment by DmitrySoshnikov** [comment]
A separate package [eslint-plugin-optimize-regex](https://www.npmjs.com/package/eslint-plugin-optimize-regex) for ESLint plugin was built instead, and it's sufficient.

**Comment by slevithan** [comment]
It would still be very nice to have an optimizer Babel plugin. E.g. I would use it in [babel-plugin-transform-regex](https://github.com/slevithan/babel-plugin-transform-regex).
