### ISSUE TITLE
Transform/runtime: Implement "named capturing groups"

### ISSUE THREAD

**Issue by DmitrySoshnikov** [DmitrySoshnikov/regexp-tree#54]
Parser support for **named capturing groups** has been added in ~[issue #28](https://github.com/DmitrySoshnikov/regexp-tree/issues/28)~. It's an ECMAScript [proposal](https://github.com/tc39/proposal-regexp-named-groups) at stage 3.

To be able to use it in older engines, we can translate:

```js
/(?<year>\d{4})-(?<month>\d{2})-(?<day>\d{2})/
```

Into:

```js
new RegExpTree(/(\d{4})-(\d{2})-(\d{2})/, ['year', 'month', 'day']);
```

The `regexpTree` creates a lightweight facade wrapper on top of ES6-compatible regexp, and provides the same API (`test`, `exec` methods, etc).

```js
class RegExpTree {
  constructor(re, groups) {
    this.re = re;
    this.groups = groups;
  }

  test(string) {
    return this.re.test(string);
  }
 
  exec(string) {
    const result = this.re.exec(string);

    // process `result`, and attach `groups`:
    // result.groups.year -> result[1]
    // result.groups.month -> result[2]
    // etc.
  }
  ...
}
```

As well as overrides `String.prototype.match` method to attach group names to the `groups` property on the match result.

```js
const originalMatch = String.prototype.match;

String.prototype.match = function(regexp) {
  // Simple regexp.
  if (!(regexp instanceof RegExpTree) {
    return originalMatch.call(this, regexp);
  }
  
  // RegExpTree. 
  return regexp.exec(this);
};
```

**Comment by hg42** [comment]
that's 1/3 of what I currently do with regexp-tree.

Your example has only named groups. You can also have unnamed groups.
You need to collect an array of both group names and indexes of regular capturing groups (set name = index).

**Comment by DmitrySoshnikov** [comment]
@hg42, good point, yeah, the second parameter should be map from group name to the index. I think unnamed groups share the same index? I.e. this matches `aaa`:

```js
/(?<foo>a)\1\k<foo>/
```

So perhaps:

```js
/(x)(?<year>\d{4})-(y)(?<month>\d{2})-(?<day>\d{2})/
```

Would give:

```js
new RegExpTree(/(x)(\d{4})-(y)(\d{2})-(\d{2})/, {year: 2, month: 4, day: 5});
```

**Comment by hg42** [comment]
yes, named groups count => x=1 y=3.

you can also use `[null, 1, "year", 3, "month", "day"]`, then you simply loop through the array and store `names[i]: originalMatch[i]` in matches.groups, So, `matches.groups["3"]` would result in "y".

**Comment by DmitrySoshnikov** [comment]
Transform part is done in https://github.com/DmitrySoshnikov/regexp-tree/commit/f1233b904f22d2a82b8ed24d8290e7db9e98c984 and  https://github.com/DmitrySoshnikov/regexp-tree/commit/7fb4b3428e55a8aec29669ecca2f3d51a9ff0099.

**Comment by DmitrySoshnikov** [comment]
Local runtime support has been added in https://github.com/DmitrySoshnikov/regexp-tree/commit/0e6a9ff70679b15bc475574b2ab361bddadc2d84.
