### ISSUE TITLE
Transform: implement "dotAll" s flag

### ISSUE THREAD

**Issue by DmitrySoshnikov** [DmitrySoshnikov/regexp-tree#55]
The "dotAll" `s` flag enables `\n` to match as well:

```js
/./s
```

Can be translated to:

```js
/[\0-\uFFFF]/
```

Or into:

```js
/[^]/
```

**Comment by DmitrySoshnikov** [comment]
@mathiasbynens, will both of the work equivalently, and can you advise please, which better to choose?

**Comment by hg42** [comment]
or `[\s\S]`

**Comment by DmitrySoshnikov** [comment]
@hg42, yep, this works too. The `/[^]/` seems the shortest one; otherwise, optimizer will have more job translating `/[\0-\uFFFF]/`, or `[\s\S]` to `[^]` :P

**Comment by mathiasbynens** [comment]
`[^]` is shortest but doesn’t work in IE < 9.

[My transpiler](https://mothereff.in/regexpu#input=const+regex+%3D+%2Ffoo.bar%2Fs%3B%0Aconsole.log%28%0A++regex.test%28%27foo%5Cnbar%27%29%0A%29%3B%0A%2F%2F+%E2%86%92+true&dotAllFlag=1) translates it to `[\0-\uFFFF]` when the Unicode flag is not set, and `[\0-\u{10FFFF}]` when the `u` flag is set.

**Comment by hg42** [comment]
I think, `[\0-\uFFFF]` and `[\0-\u{10FFFF}]` are most explicit.
These do not depend on how the engine interprets "not nothing" or how the char sets `\s` and `\S` are defined (they may not exactly complement each other, see `\W`).

However, someone not getting right `[\s\S]`, might also exclude line ends from the explicit range by intention.

`\s` per definition does include line ends, right? I don't see much possibilities, someone could do this wrong. But still there is a (slight?) chance that other whitespace or some special characters might be missing.
So if `\S` may not exactly complement `\s`, what about `(?:.|\s)`. Dot should really include everything but line ends and `\s` definitely includes line ends so it should fill exactly that gap.
Unfrotunately it's a slightly more complex construct for the engine and might even be slower in runtime.

**Comment by hg42** [comment]
> (actually, now I think it's a good use-case to add to the optimizer anyways).

it's also a good example, that the set of optimizations depends heavily on what you want to accomplish with the optimizing pass. Obviously we all want to optimize in a different direction.

You might want to get a small or a quick regexp for only one target engine (another dependency) or you might want to get a most portable regexp. Or it should be unicode centric.

My optimization desires are always kind of "do all in this direction, but obey that rule(s)".
E.g. "optimize to the fastest, smallest regexp but don't break compatibility from IE8 up".
Or "optimize to fastest regexp running on javascript 5".

For such demands only one optimization rule can ruin the whole thing.

So @DmitrySoshnikov please keep the rule sets in mind...

**Comment by DmitrySoshnikov** [comment]
OK, so seems `[\0-\uFFFF]` is a more appropriate translation then (for performance, than non-capture group, and supported in older engines).

I set up [compat-transpiler](https://github.com/DmitrySoshnikov/regexp-tree/tree/master/src/compat-transpiler) module in https://github.com/DmitrySoshnikov/regexp-tree/commit/bf8584ff2d3af09777164587c16ff801376eb7ae, and added "dotAll" implementation. Please let me know if you see any issues[1].

@hg42, yes, agreed, that users may want to choose only specific optimizations. In the `compat-transpiler` I used this approach with passing an (optional) whitelist.

[1] (as mentioned, I'd do pull-requests instead of committing directly to master, in case if someone will be interested in actually reviewing them, and find time for it)

**Comment by DmitrySoshnikov** [comment]
Closing this, feel free to comment if find any issues.
