### ISSUE TITLE
Optimizer: implement "remove empty groups" transform

### ISSUE THREAD

**Issue by DmitrySoshnikov** [DmitrySoshnikov/regexp-tree#56]
We should remove empty groups:

```
/a()/ -> /a/
/a(?:)/ -> /a/
```

NOTE: removing a capturing group potentially changes semantics (the number of groups will be different), but this seems should  be fine -- I cannot imagine any actual use-case when an empty group should be used, so this is mostly a "lint rule".

**Comment by hg42** [comment]
I am not sure...

The user would not create an empty group manually.

So it is a result of some algorithm. This algorithm probably counts the group.
The developer either didn't take into account that this can happen or he doesn't care about (performance is unimportant etc.).

The problem of optimizing an internal set of rules is that it is hidden and can be extended by rules you didn't expect.

That's one reason I want to be able to configure this explicitely. Defaults are ok, though.
I would prefer if the set(s) of rules would be public and can be copied and modified..

**Comment by DmitrySoshnikov** [comment]
@hg42, yep, agreed, we'll need to change optimizer API to be similar of compat-transpiler, which [accepts a whitelist](https://github.com/DmitrySoshnikov/regexp-tree/blob/master/src/compat-transpiler/index.js#L18) of the transforms needed to be applied.

Technically, we could also accept any other transform there, not only a string name of the default transforms: if a transform is a string, it's a name, otherwise we just take it as is, assuming it's an actual instance of the handler is passed.

Also, I agree that empty groups should not appear explicitly in a regexp, and mostly are a result of some intermediate results of transformations. Although, there might be some "typos", that's why I mentioned it's mostly a "lint rule".

**Comment by DmitrySoshnikov** [comment]
> So it is a result of some algorithm. This algorithm probably counts the group.

FWIW, I added `number` property in a `Group` node, so at least don't need to count in the original tree. Also, I opened #59 to discuss some "consistency utils", since many properties can become unsync after the first transform in a pipeline is executed.

**Comment by Golmote** [comment]
@DmitrySoshnikov #104 fixed half of this issue.

Regarding the removal of empty capturing groups, I think we should not do this transform by default. We might want to allow the user to activate it somehow, then they are responsible if the semantics is changed.

Also, empty capturing groups might appear explicitly in PCRE regexps.
Consider the following non-capturing group using `(?|` that resets the number of the captures in each alternative (https://www.pcre.org/current/doc/html/pcre2syntax.html#SEC13):
`/(?|()(a)|(b)(c))/` captures `{1: '', 2: 'a'}` or `{1: 'b', 2: 'c'}`. I've already found myself doing so explicitely in PHP.

**Comment by DmitrySoshnikov** [comment]
Yeah, removing non-capturing is enough here, messing with capturing groups removal may change semantics, and cause some bugs.
