### ISSUE TITLE
reordering `a(b)` to `b(a)` does not set parentPath correctly (parent not in sync with parentPath)

### ISSUE THREAD

**Issue by hg42** [DmitrySoshnikov/regexp-tree#60]
I have a test case, where the parents get out of sync.

I think there is something wrong or missing in my latest `setChild` code or perhaps in `getForNode`.

Originally I used `replace()` in the test case and blamed it for the error.
But now I have rewritten it using `setChild`. I generally think `replace()` shouldn't be used for such reorders. But now I have a very similar error.

I already tried to find the bug, but I didn't succeed, yet.
My debugger is non-functional currently, so I only try to use logging and good conclusions.

Perhaps someone else wants to try?

But of course I'm not out of options (I guess I never will), so I'll try more myself.
I just wanted to let everyone know, that there is a problem.

This is the test case:
```js
  it('replaces with already used node with another parent', () => {
    const ast = parser.parse('/a(b)/');

    const bodyPath = new NodePath(ast.body);
    const aCharPath = bodyPath.getChild(0);
    const groupPath = bodyPath.getChild(1);
    const bCharPath = groupPath.getChild();
    const aNode = aCharPath.node;
    const bNode = bCharPath.node;

    bodyPath.node.mark = "body";
    groupPath.node.mark = "group";

    // swap a and b
    groupPath.setChild(aNode);
    bodyPath.setChild(bNode, 0);

    // body and group still at same position
    expect(bodyPath.node.mark).toEqual('body')
    expect(groupPath.node.mark).toEqual('group')
    expect(bodyPath.getChild(1).node.mark).toEqual('group')
    // second is Char 'a' in the Group
    expect(bodyPath.getChild(1).getChild().node.type).toEqual('Char')
    expect(bodyPath.getChild(1).getChild().node.value).toEqual('a')
    // now the parent of 'a' is the Group
    expect(bodyPath.getChild(1).getChild().parent.mark).toEqual('group')
    
    // ...
  });
```
the last `expect` fails like this:
```
    Expected value to equal:
      "group"
    Received:
      "body"
```

If you add this (instead of the last `expect`):
```js
expect(bodyPath.getChild(1).getChild().parentPath.node)
 .toBe(bodyPath.getChild(1).getChild().parent)
```
you get this error:
```
    - Expected
    + Received

    Object {
    -  "expressions": Array [
    -    Object {
    -      "kind": "simple",
    -      "symbol": undefined,
    -      "type": "Char",
    -      "value": "b",
    -    },
    -    Object {
    -      "capturing": true,
    -      "expression": Object {
    -        "kind": "simple",
    -        "symbol": undefined,
    -        "type": "Char",
    -        "value": "a",
    -      },
    -      "mark": "group",
    -      "number": 1,
    -      "type": "Group",
    -    },
    -  ],
    -  "mark": "body",
    -  "type": "Alternative",
    +  "capturing": true,
    +  "expression": Object {
    +    "kind": "simple",
    +    "symbol": undefined,
    +    "type": "Char",
    +    "value": "a",
    +  },
    +  "mark": "group",
    +  "number": 1,
    +  "type": "Group",
     }
```
so the node in the `parentPath` of 'a' is the body (which is wrong) and the `parent` is the group (which is correct). Of course they should be identical (=group).

@DmitrySoshnikov you added the same `NodePath.getForNode` to `replace()` like I did.
I still think, this is correct.

EDIT: I removed some lines about getForNode and index parameter, because that's not ready to be discussed

**Comment by hg42** [comment]
ok, found it.
Some asserts at interesting places helped a lot...
```js
  static getForNode(node, parentPath = null, prop = null, index = -1) {
    if (!node) {
      return null;
    }

    if (!NodePath.registry.has(node)) {
      NodePath.registry.set(
        node,
        new NodePath(node, parentPath, prop, index == -1 ? null : index)
      );
    }

    let path = NodePath.registry.get(node);

    if (parentPath !== null) {
      path.parentPath = parentPath;
      path.parent = path.parentPath.node;     // <-------------------- here
    }

    if (prop !== null) {
      path.property = prop;
    }

    if (index >= 0) {
      path.index = index;
    }

    return path;
  }
```
I am not sure why setting the parent helps when in the test the parentPath was wrong.
But it works this way.
I'll send a PR soon.

**Comment by DmitrySoshnikov** [comment]
@hg42, yes, the `parent` got unsync on reorder, so should be updated.

So the `traverse`/`NodePath` is becoming one of the complex modules of the system (when it's not easy to track complicated reordering of nodes/paths), so thanks for catching this, and fixing.

BTW, I have suspicions, that even more complex re-shuffles can make `parentPath` unsync.

E.g.

```js
/(a(b(cd)e)f)/
```

Is transformed to:

```js
/(ae)f)(b(cd)/
```

The `parentPath` of the `(cd)` group might be still unsync (even though `parentPath` of the whole `(b(cd)` is updated).

Perhaps, we'll need to invalidate the whole "path" in the parent chain.

**Comment by DmitrySoshnikov** [comment]
Ah, never mind, seems parent of `(cd)` in my example should correctly stay as as :) so should be fine.
