### ISSUE TITLE
Parser: implement `x` flag

### ISSUE THREAD

**Issue by DmitrySoshnikov** [DmitrySoshnikov/regexp-tree#62]
When `x` flag is used in a regexp, whitespace are ignored, and #-comments can be used.

This is not a standard flag (yet) of JavaScript regexes, however, in order to support different syntaxes (pcre, python etc), we can add support of `x` to the main parser.

In the future, if different syntaxes differ too much, we'll have to fork grammar file, and implement one per syntax. Currently handling `x` is trivial in the main grammar, so not forking yet.

```regex
/
  # A regular expression for date.

  (?<year>\d{4})-    # year part of a date  
  (?<month>\d{2})-   # month part of a date
  (?<day>\d{2})      # day part of a date

/x

```

Re: JavaScript: this can also be handled in compat-transpiler (and later proposed for standardization).

**Comment by DmitrySoshnikov** [comment]
Fixed in https://github.com/DmitrySoshnikov/regexp-tree/commit/18473e8276a1f362990e7fae920e90201d2c5c25.

**Comment by hg42** [comment]
nice, thanks...
I now can throw away part of my solution and set x-flag instead.
Just keep on making me  unemployed :-)
no offense, I really appreciate that, I can concentrate on the real problem now, if you don't take over this, too.

**Comment by DmitrySoshnikov** [comment]
@hg42, lol, sounds good 😆
