### ISSUE TITLE
exec(...): exception if javascript RegExp fails

### ISSUE THREAD

**Issue by hg42** [DmitrySoshnikov/regexp-tree#64]
I got an exception:
```
    result.groups = {};
                  ^

TypeError: Cannot set property 'groups' of null
```
which is internal stuff.

So, `result` should be checked in src/compat-transpiler/runtime/index.js:
```js
  /**
   * Facade wrapper for RegExp `exec` method.
   */
  exec(string) {
    const result = this._re.exec(string);

    if (!this._groups) {
      return result;
    }

    result.groups = {};
  ...
```

**Comment by DmitrySoshnikov** [comment]
ah, good catch, I'll take a look, or PR is as always welcome :)

**Comment by DmitrySoshnikov** [comment]
OK, fixed in https://github.com/DmitrySoshnikov/regexp-tree/commit/777646cbb27a81fdc792a331744572cc76ce7340.

**Comment by hg42** [comment]
ok, you were faster (and the test is better placed), thanks
