### ISSUE TITLE
Implement transform module

### ISSUE THREAD

**Issue by DmitrySoshnikov** [DmitrySoshnikov/regexp-tree#7]
The `transform` method is a wrapper on top of "parse-traverse-generate" tool chain. Getting a regular expression string, and the nodes handler, `transform` should return a new (transformed) regular expression.

The issue depend on ~[issue #5](https://github.com/DmitrySoshnikov/regexp-tree/issues/5)~.

An example of manual traversal, and code generation is shown in the [Using traversal API](https://github.com/DmitrySoshnikov/regexp-tree#using-traversal-api) section. A `transform` version of it should look like:

```js
const regexpTree = require('regexp-tree');

const re = regexpTree.transform('/[a-z]{1,}/', {
  // Handle "Quantifier" node type,
  // transforming `{1,}` quantifier to `+`.
  onQuantifier(node) {
    // {1,} -> +
    if (
      node.type === 'Range' &&
      node.from === 1 &&
      !node.to
    ) {
      node.type = '+';
      delete node.from;
    }
  },
});

console.log(re); // '/[a-z]+/'
```

**Comment by shvaikalesh** [comment]
What should be return value of `transform`?

1. Receives `string`, returns `string`. Receives `RegExp`, returns `RegExp`.
  - It is not cool (at least in langs without "native" overloading) when return value depends on provided one.
2. Always return `string`.
  - It is a bit awkward to make `RegExp` from `string`.
3. Always return `RegExp`.
4. Return some `Result` object with `toString` and `toRegExp`.

**Comment by mathiasbynens** [comment]
My vote goes to option 4.

**Comment by DmitrySoshnikov** [comment]
Agreed, option 4 seems the most optimal.

So the `transform` module in contrast with `traverse` will focus on exactly _transformation_, providing convenient API methods for AST manipulation. Thus, as was [discussed](https://github.com/DmitrySoshnikov/regexp-tree/pull/31#issuecomment-290971172), it'd be fragile to attach API methods directly on `this` (where `this` is a handler), or on a node (we don't want to modify original AST outside of user's modifications).

In https://github.com/DmitrySoshnikov/regexp-tree/commit/d1b0110fda4f8fcb4ed9a7d99536b9046ebd5c8f I set up a basic RFC, feel free to change/provide better alternative implementation in case. The idea is:

- transform accepts a "regexp" in any format (string/regexp/ast)
- it returns a `TransformResult` instance (option 4 from the above)
- it accepts a list of handlers (or one handler for convenience)
- a handler is either a _raw handler_ (in which case it doesn't have access to transform API)
- or a handler is a _function_ which receives as a parameter `TransformApi`, and has access to all convenient methods, such as `api.removeNode(node)`, `api.replaceNode(node, newNode)`, etc.

Example: 

```js
const regexpTree = require('regexp-tree');

const re = regexpTree.transform('/[a-z]{1,}/',
  api => {
    // Handle "Quantifier" node type,
    // transforming `{1,}` quantifier to `+`.
    onQuantifier(node) {
      // {1,} -> +
      if (
        node.type === 'Range' &&
        node.from === 1 &&
        !node.to
      ) {
        api.replaceNode(node, {
          type: 'Quantifier',
          kind: '+',
          loc: {
            start: node.loc.start,
            end: node.loc.start + 1,
          },
        });
      }
    },
  },
});

console.log(re.toRegExp()); // /[a-z]+/
```

The _function_ version of a handler implements a _plugin_. A separate npm modules will be able to implement a needed plugin just exporting a function which receives the transform API.

The `transform.transform` internally recognizes a handler format, and if it's a function, calls it, passing the API object as a parameter (a similar approach used in Babel).

Thoughts?

**Comment by DmitrySoshnikov** [comment]
Actually, one more, and probably a better alternative is to use a `NodePath` wrapper on top of a node (similar to how Babel traversal uses). It'll store any needed state (a node, parent, prop, index), meta information, and API methods.

```js
const regexpTree.transform('/[a-z]{1,}/', {
  onChar(path) {
    const {node, parent} = path;
    if (...) {
      path.removeNode(node);
    }
  }
});
```

**Comment by DmitrySoshnikov** [comment]
Fixed in https://github.com/DmitrySoshnikov/regexp-tree/commit/277c2d6d28bab3102975cd93b64d5419db008e32.
