### ISSUE TITLE
`/\e/u` should throw

### ISSUE THREAD

**Issue by mathiasbynens** [DmitrySoshnikov/regexp-tree#8]
`/\e/u` is an invalid regular expression: https://mathiasbynens.be/notes/es6-unicode-regex#impact-syntax

So instead of parsing, I’d expect this to throw:

```
$ regexp-tree -e '/\e/u'
{
  "type": "RegExp",
  "body": {
    "type": "Char",
    "value": "e",
    "kind": "simple",
    "escaped": true
  },
  "flags": [
    "u"
  ]
}
```

**Comment by DmitrySoshnikov** [comment]
Good catch! Currently there is a bug then with parsing `\u{...}` notation as well -- it's always is parsed as a unicode (even without `u` flag) instead of alternative.
