### ISSUE TITLE
Incorrectly handles escaped forward slashes as duplicates

### ISSUE THREAD

**Issue by BrainMaestro** [DmitrySoshnikov/regexp-tree#83]
`[\\]` is transformed to `[\]` which is incorrect. I looked around trying to fix it, but I'm not sure exactly how to. [This](https://github.com/DmitrySoshnikov/regexp-tree/blob/master/src/optimizer/transforms/char-class-remove-duplicates-transform.js#L21) is the relevant part though.

**Comment by DmitrySoshnikov** [comment]
Thanks, good catch. The issue was actually in the unescape optimizer transform, fixed in https://github.com/DmitrySoshnikov/regexp-tree/commit/0d844999379287ebd0797463c20e08f672150c34, and in the `0.0.52`.
