### ISSUE TITLE
Optimizer doesn't seem to work on Windows

### ISSUE THREAD

**Issue by kurtextrem** [DmitrySoshnikov/regexp-tree#84]
Am I doing something wrong? http://prntscr.com/g3h4o4

**Comment by kurtextrem** [comment]
Oh, it seems to work without the '.

**Comment by DmitrySoshnikov** [comment]
@kurtextrem, thanks, I'll take a look.

**Comment by DmitrySoshnikov** [comment]
Yeah, this seems a specifics of the Windows command line parameters. To unify both *nix, and Windows, we can probably check whether first and last symbols are equal to `'`, and strip them, if the platform is Windows.

So here where we [get the expression](https://github.com/DmitrySoshnikov/regexp-tree/blob/master/bin/regexp-tree#L38), we can check something like this:

```js
expression = normalize(expression);
```

And add the `normalize` function:

```js
function normalize(expression) {
  if (!shouldStripQuotes(expression)) {
    return expression;
  }

  // For Windows strip ' at the beginning and end.
  return expression.slice(1, -1);
}

function shouldStripQuotes(expression) {
  return os.platform() === 'win32' && (
    (expression[0] === "'" && expression[expression.length - 1] === "'") ||
    (expression[0] === '"' && expression[expression.length - 1] === '"')
  );
}
```

I can take a look later on, and will of course appreciate a pull request in case you'd like to fix it for Windows :)

**Comment by kurtextrem** [comment]
I'll give it a try! :)
