### ISSUE TITLE
Optimizer should not unescape |

### ISSUE THREAD

**Issue by Golmote** [DmitrySoshnikov/regexp-tree#91]
Currently, `|` is unescaped by optimizer, when used outside a character class.

Test:
```js
console.log(regexpTree.optimize(/a\|b/).toRegExp());
```

Current result:
```js
/a|b/
```

Expected result:
```js
/a\|b/
```

**Comment by DmitrySoshnikov** [comment]
Thanks! Fixed in https://github.com/DmitrySoshnikov/regexp-tree/commit/fe1e67d423d672d4851d45c861a37266393f789e.
