### ISSUE TITLE
Error thrown when using range \xA0-\uFFFF

### ISSUE THREAD

**Issue by Golmote** [DmitrySoshnikov/regexp-tree#92]
When using range `[\xA0-\uFFFF]` in a character class, the parser throws the following error:

```
SyntaxError: Range \xA0-\uFFFF out of order in character class
```

I guess this type of range is unusual, but I'm pretty sure it's valid (and AFAICT it works in browsers).

I think the same error is thrown when combining a simple char with a char code, like `a-\xA0` or `a-\uFFFF`.

**Comment by DmitrySoshnikov** [comment]
Yeah, we should check which values come here: https://github.com/DmitrySoshnikov/regexp-tree/blob/master/src/parser/regexp.bnf#L180
