### ISSUE TITLE
Optimizer should not unescape - in character class

### ISSUE THREAD

**Issue by Golmote** [DmitrySoshnikov/regexp-tree#93]
Currently, `-` is unescaped by optimizer, when used inside a character class.

Test:
```js
console.log(regexpTree.optimize(/[a\-c]/).toRegExp());
```

Current result:
```js
/[a-c]/
```

Expected result:
```js
/[a\-c]/
```

**Comment by DmitrySoshnikov** [comment]
Good catch! We should add `-` here: https://github.com/DmitrySoshnikov/regexp-tree/blob/master/src/optimizer/transforms/char-escape-unescape-transform.js#L44. I can take a look later on tonight (or if you reach it earlier, will appreciate a PR too).

```
./bin/regexp-tree -e '/[a\-c]/' -o
```

Should be:

```
Optimized: /[a\-c]/
```

**Comment by DmitrySoshnikov** [comment]
Quick bug fix is in the https://github.com/DmitrySoshnikov/regexp-tree/commit/a5e4d57e6d29e403892172ab95f796ab001ce0ad. We can do more sophisticated check in a separate diff (TODO is left).
