### ISSUE TITLE
Optimizer: implement "remove duplicates" transform for disjunction

### ISSUE THREAD

**Issue by Golmote** [DmitrySoshnikov/regexp-tree#94]
It would be nice if the optimizer removed duplicates in disjunctions:

`/ab|ab/ -> /ab/`

**Comment by DmitrySoshnikov** [comment]
Yep, would be a good one. I can take a look later, and of course will appreciate a PR in case you wanna build this plugin. It would be similar to this transform: https://github.com/DmitrySoshnikov/regexp-tree/blob/master/src/optimizer/transforms/char-star-to-plus-transform.js#L24-L34. We just need to check a sibling, and whether they have the same source, and remove one of them.

**Comment by Golmote** [comment]
Thank you for the quick answer !
I tried to dig into this to provide you with a PR, but I think I'm missing a point somewhere. Disjunctions seem to have `left` and `right` properties instead of `expressions`. I can't seem to find appropriate methods in NodePath to navigate those.

**Comment by DmitrySoshnikov** [comment]
Yep, the Disjunction (aka "OR") operation has `left` and `right` nodes. Notice, it's also left-associative, that is:

```
a|a|a
```

is actually:

```
((a|a)|a)
```

still having only one left-, and one right- hand side.

The `NodePath.getForNode(...)` returns a path for a node. Probably something like this should work (haven't checked yet):

```js
Disjunction(path) {

  const leftPath = NodePath.getForNode(node.left);
  const rightPath = NodePath.getForNode(node.right);

  if (leftPath. hasEqualSource(rightPath)) {
    path.replace(node.left);
  }
}
```
