### ISSUE TITLE
Optimizer: \{ and \} must not be unescaped all the time

### ISSUE THREAD

**Issue by Golmote** [DmitrySoshnikov/regexp-tree#95]
Currently, `{` and `}` are always unescaped by optimizer. You should consider the few cases where it might change the meaning, though.

Test:
```js
console.log(regexpTree.optimize(/a\{3\}/).toRegExp());
```

Current result:
```js
/a{3}/
```

Expected result (or at least one option):
```js
/a\{3}/
```

**Comment by DmitrySoshnikov** [comment]
Yeah, clearly a bug, thanks for the catch! We should consider `\{` in https://github.com/DmitrySoshnikov/regexp-tree/blob/master/src/optimizer/transforms/char-escape-unescape-transform.js#L48.

**Comment by DmitrySoshnikov** [comment]
Quick bug fix is in the https://github.com/DmitrySoshnikov/regexp-tree/commit/a5e4d57e6d29e403892172ab95f796ab001ce0ad. We can do more sophisticated check in a separate diff (TODO is left).
